rm-controls/rm_manual

include/rm_manual/chassis_gimbal_shooter_manual.h, src/chassis_gimbal_shooter_manual.cpp
1. 现象：使用键鼠操作时，如果发射的模式为stop，那么第一次点击会先进push模式，但是此时可能由于拨盘期望位置与实际位置相差过大，导致不能执行shooter controller中push函数中的拨盘setcommand函数，以及变量"last_shoot_time_"的更新。这会导致满足判断是否卡弹的逻辑，导致一直在block模式，无法正常发射。
2. 解决方法：将点击鼠标左键的逻辑改为：当鼠标左击时，如果当前为stop模式，先进入ready模式，第二次点击后才进入push模式，这样可以让拨盘执行normalize()，从而通过push的判断，目前在3号进行了测试。
=> Modify the logic of clicking the left mouse button

include/rm_manual/chassis_gimbal_shooter_manual.h, src/chassis_gimbal_shooter_manual.cpp
1. 增加了一个用于切换相机的键位。
2. 实现：当按下键位时，如果当前使用的是长焦会向话题发一个表示短焦的字符串；相机节点接收后，会根据这个字符串决定哪个节点阻塞，哪个推流，反过来一样。
=> Add key for switching camera

src/chassis_gimbal_shooter_manual.cpp
问题：由于英雄有切换相机的需求，所以在chassis gimbal shooter manual中构造了一个camera switch command sender，但是步兵不需要这个功能，并不需要构造。按照现在的代码，如果配置文件中没有相关参数会导致报错
解决方法：判断配置文件中是否有“camera”，没有就不构造camera switch command sender
=> Determine whether to construct a camera switch command sender based on whether there are parameters

include/rm_manual/chassis_gimbal_shooter_cover_manual.h, include/rm_manual/chassis_gimbal_shooter_manual.h, include/rm_manual/manual_base.h, src/chassis_gimbal_shooter_cover_manual.cpp, src/chassis_gimbal_shooter_manual.cpp, src/manual_base.cpp
对代码进行了以下修改：
1. 增加一个话题订阅者以及回调，接收视觉发过来的数据判断是否发射，这个用于打旋转装甲板
2. 用e来切换自瞄击打旋转装甲板和打普通装甲板
3. 增加g用来识别紫色装甲板
=> Added hero and standard self-aiming mode switching buttons

include/rm_manual/chassis_gimbal_shooter_cover_manual.h, include/rm_manual/chassis_gimbal_shooter_manual.h, src/chassis_gimbal_shooter_cover_manual.cpp, src/chassis_gimbal_shooter_manual.cpp
在chassis_gimbal_shooter_manual中使用ctrl q用来校准拨盘，同时在chassis_gimbal_shooter_cover_manual中重写ctrlQPress函数，校准拨盘、云台、弹仓。
=> Add function for shooter calibration of key ctrl q

include/rm_manual/chassis_gimbal_manual.h, include/rm_manual/chassis_gimbal_shooter_cover_manual.h, include/rm_manual/chassis_gimbal_shooter_manual.h, include/rm_manual/dart_manual.h, include/rm_manual/manual_base.h, src/chassis_gimbal_manual.cpp, src/chassis_gimbal_shooter_cover_manual.cpp, src/chassis_gimbal_shooter_manual.cpp, src/dart_manual.cpp, src/manual_base.cpp
原来机器人的上电校准数据源是裁判系统的数据，该数据会显示机器人底盘，云台和发射机构是否处于上电状态。考虑到官方裁判系统和机器人串口并不稳定，将校准的数据源改为/actuator_states话题，根据话题是否有数据来判断上电情况。这种方式能够避免因为串口断连，数据错误引起的无法校准，同时在掉can重连的情况下也可以重新进行校准。
校准逻辑：在参数文件中规定底盘，云台，发射机构需要校准的电机，程序会检索相应电机的时间戳，若时间戳触发了一个重新更新的上升沿则重置相应的校准队列。
目前在步兵和平衡步兵上进行了测试。
因为误操作的原因，平衡步兵的侧向对敌被合并进了改分支且原分支已被删除，所以本分支有侧向对敌的代码。
=> Modify calibration conditions.

include/rm_manual/chassis_gimbal_shooter_manual.h, include/rm_manual/manual_base.h, src/chassis_gimbal_shooter_manual.cpp, src/main.cpp, src/manual_base.cpp
根据新的超电硬件和固件修改了manual中超电部分的逻辑。
改动有原先的点按b切换充电的功能改为长按触发，修改了自动充电的处罚条件，替换capacity msg名字等
本pr在开发中由于测试需要，是基于另一个[pr](https://github.com/rm-controls/rm_manual/pull/53)进行修改
=> Update for new power management

src/chassis_gimbal_shooter_cover_manual.cpp
修复超电模式切换中出现的问题。
超点进入NORMAL无法切换其他状态的原因在cover的判断中，会强制设置模式为NORMAL。首先切换模式在开关弹仓的按键和拨杆中已经写好了，状态机里的是多余的;其次也正是这个的原因超电无法设置其他的状态
=> Fixed capacity mode change bug

include/rm_manual/manual_base.h, src/manual_base.cpp
1. 由于dbus的时间戳有时会有超过0.1s的时间没有更新，而此时遥控是开着的，会导致程序上认为遥控关闭，调用remoteControlTurnOff函数将state设为IDLE，当过了这一小段时间后，时间戳继续更新，会调用remoteControlTurnOn函数。但是由于state是上升沿触发，而上述过程中不会触发上升沿，因此state将一直保持IDLE，需要拨一下右拨杆触发上升沿切换state。
2. 解决方法：在高电平时设置state
=> Set the state when the right switch is high

include/rm_manual/chassis_gimbal_shooter_manual.h, src/chassis_gimbal_shooter_manual.cpp
1. 修改了切换紫色目标的按键函数的逻辑
2. 将manual_to_referee_pub_data_的det_armor_target修改为从switch_armor_target_srv_获取
=> Modify the logic of switching to purple target

include/rm_manual/chassis_gimbal_shooter_cover_manual.h, include/rm_manual/chassis_gimbal_shooter_manual.h, src/chassis_gimbal_shooter_cover_manual.cpp, src/chassis_gimbal_shooter_manual.cpp, src/manual_base.cpp
1. 由于轻量化英雄需要云台校准，所以将gimbal calibration相关代码移动到ChassisGimablShooterManual中
2. 由于英雄云台没有接电源管理gimbal，而是通过电子开关由Chassis控制上电，因此在ChassisOutOn中调用gimbal_calibration_->reset()，即校准云台，在ChassisGimablShooterCoverManual中重写ChassisOutOn.
=> Move gimbal calibration related code to ChassisGimablShooterManual

src/chassis_gimbal_shooter_cover_manual.cpp
=> Fix bugs that standard enter slow speed when opening the cover.

include/rm_manual/manual_base.h, src/manual_base.cpp
考虑到程序不应该订阅actutor state话题进行判断，重新使用裁判系统的数据进行校准
=> Reuse referee calibrate.

include/rm_manual/dart_manual.h, include/rm_manual/manual_base.h, src/dart_manual.cpp
由于在父类中多加了无参数的左拨杆高电平触发函数，导致重载后的chassis_gimbal_shooter_manual中有参数的同名左拨杆高电平触发函数爆红（但是可以通过编译）。为了解决爆红，删除掉父类中的无参数的左拨杆高电平触发函数，并取消dart_manual中的左拨杆高电平触发函数重载。
先前的自动模式没有考虑到：在比赛开始后、飞镖门完全开启时，若此时前哨站被击破，则会出现飞镖架未移动到基地位置时就再次发射的情况。在本情况的基础上，即使飞镖架移动到基地位置再发射，也可能会出现因**飞镖发射时飞镖门恰好即将关闭**，导致飞镖以基地速度射在正在关闭的飞镖门上。（2023中部赛区对局桂电出现的情况）
本pr解决上述问题的大致方法是：禁止移动中发射；禁止飞镖门开启时，第一次射击前哨站状态切换到射击基地状态时再次发射。
确保不会出现连续击中不计入伤害的情况。
从单个参数记录方式变为二维数组记录方式。
=> Fixed unreasonable overload error and optimized  the auto mode

include/rm_manual/chassis_gimbal_shooter_manual.h, src/chassis_gimbal_shooter_manual.cpp
=> Update the method of rotate yaw and raise pitch

include/rm_manual/chassis_gimbal_shooter_cover_manual.h
删除一些没用到以及与基类重复的event，防止后面继承父类的子类无法调用。
=> Delete unused event.

include/rm_manual/engineer2_manual.h, include/rm_manual/engineer_manual.h, include/rm_manual/manual_base.h, launch/load.launch, src/chassis_gimbal_manual.cpp, src/engineer2_manual.cpp, src/engineer_manual.cpp, src/main.cpp, src/manual_base.cpp
Merge manual code from 2024 Engineer.
=> Merge rm manual of 2024 Engineer.

include/rm_manual/chassis_gimbal_shooter_cover_manual.h, src/chassis_gimbal_shooter_cover_manual.cpp
Add dynamic-speed gyro on standard.
=> Change constant-speed gyro to dynamic-speed gyro.

include/rm_manual/chassis_gimbal_shooter_manual.h, src/chassis_gimbal_shooter_manual.cpp
实现了英雄机器人可以通过按下ctrl+z、ctrl+x来进行图传位置的上下微调，可以按下ctrl+q来恢复默认吊射图传角度。
=> Achieved the function of adjusting the position of image transmission

include/rm_manual/manual_base.h, src/manual_base.cpp
=> Modify chassis power assignment

include/rm_manual/chassis_gimbal_manual.h, include/rm_manual/chassis_gimbal_shooter_manual.h, src/chassis_gimbal_manual.cpp, src/chassis_gimbal_shooter_manual.cpp
将英雄部署模式和云台traj模式结合，优化英雄吊射由于imu零飘的影响，以及优化traj模式下键鼠灵敏度。
=> Set traj mode for deploy and the traj scale
