rm-controls/rm_manual

- include/rm_manual/chassis_gimbal_shooter_manual.h
- src/chassis_gimbal_shooter_manual.cpp
> Solve the problem that left switch event does not continuously update the gimbal mode

- README.md
- include/rm_manual/common/input_event.h
- include/rm_manual/common/manual_base.h
- src/chassis_gimbal_manual.cpp
- src/chassis_gimbal_shooter_manual.cpp
> Update some manual's commit.

- include/rm_manual/chassis_gimbal_manual.h
- include/rm_manual/chassis_gimbal_shooter_cover_manual.h
- include/rm_manual/chassis_gimbal_shooter_manual.h
- include/rm_manual/common/manual_base.h
- include/rm_manual/dart_manual.h
- include/rm_manual/engineer_manual.h
- src/chassis_gimbal_manual.cpp
- src/chassis_gimbal_shooter_cover_manual.cpp
- src/chassis_gimbal_shooter_manual.cpp
- src/common/manual_base.cpp
- src/dart_manual.cpp
- src/engineer_manual.cpp
- src/main.cpp
Reverts rm-controls/rm_manual#22
> Revert "Delete referee.msg and update command sender."

- CMakeLists.txt
- package.xml
删除了cmakelist和package.xml中的roslint依赖
> Delete dependence roslint.

- include/rm_manual/engineer_manual.h
- src/engineer_manual.cpp
仅仅是统一了关于工程UI的msg的命名，没有任何功能的增加，仅是替换姓名，可以很快被合并
> Modified the msg of engineer  to 'EngineerUi'

- include/rm_manual/chassis_gimbal_shooter_cover_manual.h
- src/chassis_gimbal_shooter_cover_manual.cpp
增加z键，长按时切换到一个很低的射频用于打符，松开时切换到普通射频
> Add key z to switch the shoot frequency when hitting buff

- include/rm_manual/manual_base.h
- src/chassis_gimbal_shooter_manual.cpp
- src/manual_base.cpp
补上chassis power缺失的更新和修改了rightSwitchDownRise()进入NORMAL状态
> Fixed chassis_power update and change rightSwitchDownRise()

- include/rm_manual/chassis_gimbal_manual.h
- include/rm_manual/engineer_manual.h
- src/chassis_gimbal_manual.cpp
- src/engineer_manual.cpp
- 把原来的两档变速变为四档变速。
```
speed_change_scale: 1.0
normal_speed_scale: 0.6
exchange_speed_scale: 0.08
low_speed_scale: 0.027
fast_gyro_scale: 1
normal_gyro_scale: 0.75
exchange_gyro_scale: 0.2
low_gyro_scale: 0.025
```
> New Speed Mode.

- include/rm_manual/balance_manual.h
- src/balance_manual.cpp
> Update balance manual for mpc

- include/rm_manual/chassis_gimbal_shooter_cover_manual.h
- src/chassis_gimbal_shooter_cover_manual.cpp
增加了：在打符模式下，长按w键超过0.5s自动切回普通自瞄的功能
> Automatically exit hiiting buff mode when pressing key w

- include/rm_manual/balance_manual.h
- include/rm_manual/chassis_gimbal_shooter_manual.h
- src/chassis_gimbal_shooter_manual.cpp
1. 将英雄切换自瞄模式的按键修改为长按
2. 将自爆按键修改为长按
3. 增加按键调整摩擦轮转速的功能，通过v键增加转速，g键减小转速
4. 由于取消了吊射自瞄，所以将瞄紫色目标的按键（g键）改为减小摩擦轮转速
> Modify some key logic and add function of adjusting friction wheel speed by key

- include/rm_manual/engineer_manual.h
- src/engineer_manual.cpp
优化函数排列顺序，在servo mode和joint mode时分别采用qe和鼠标控制底盘旋转。
> Merge engineer manual.

- include/rm_manual/chassis_gimbal_shooter_manual.h
- src/chassis_gimbal_shooter_manual.cpp
> Change f_event_ to ctrl_f_event_.

- include/rm_manual/chassis_gimbal_shooter_cover_manual.h
- include/rm_manual/chassis_gimbal_shooter_manual.h
- src/chassis_gimbal_shooter_cover_manual.cpp
- src/chassis_gimbal_shooter_manual.cpp
按住z切换最低射频，松开切回原来的射频
拨杆左上0.02s内切换为最低射频，之后切换为原本的射频
> Switch shoot frequency

- include/rm_manual/chassis_gimbal_shooter_manual.h
- include/rm_manual/manual_base.h
- src/chassis_gimbal_shooter_manual.cpp
- src/manual_base.cpp
> Auto friction speed

- include/rm_manual/chassis_gimbal_shooter_manual.h
- src/chassis_gimbal_shooter_manual.cpp
> Stop gyro when robot revives.

- src/manual_base.cpp
> Add a variable to select dbus topic.

- include/rm_manual/chassis_gimbal_shooter_manual.h
- src/chassis_gimbal_manual.cpp
- src/chassis_gimbal_shooter_manual.cpp
实现英雄机器人仅有云台能动，底盘不移动，方便吊射的部署模式。
> Achieve deploy mode for hero

- src/chassis_gimbal_manual.cpp
> Add a flag for control constantly

- include/rm_manual/chassis_gimbal_shooter_cover_manual.h
- include/rm_manual/chassis_gimbal_shooter_manual.h
- src/chassis_gimbal_shooter_cover_manual.cpp
- src/chassis_gimbal_shooter_manual.cpp
> Change close gyro shortcut to Q key

- include/rm_manual/chassis_gimbal_shooter_cover_manual.h
- src/chassis_gimbal_shooter_cover_manual.cpp
> Optimize the key for hitting buff

- include/rm_manual/chassis_gimbal_shooter_cover_manual.h
- src/chassis_gimbal_shooter_cover_manual.cpp
> Fix the problem of z press

- include/rm_manual/chassis_gimbal_shooter_cover_manual.h
- src/chassis_gimbal_shooter_cover_manual.cpp
- src/chassis_gimbal_shooter_manual.cpp
使用B键，一定时间内提高使用超电的功率
调整小陀螺的功率模式为BURST
> Use the B key to increase the power of the standard burst mode

- include/rm_manual/chassis_gimbal_shooter_manual.h
- src/chassis_gimbal_shooter_manual.cpp
> Fix the x press key for hero

- src/chassis_gimbal_shooter_manual.cpp
> Add a function to change friction speed for deploy

- CMakeLists.txt
- include/rm_manual/chassis_gimbal_manual.h
- include/rm_manual/chassis_gimbal_shooter_cover_manual.h
- include/rm_manual/manual_base.h
- package.xml
- src/chassis_gimbal_manual.cpp
- src/chassis_gimbal_shooter_cover_manual.cpp
> Fix inconsistent ESC calibration timing for chassis motors
